services:
  - type: web
    name: rekal-relais
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BLACKBOX_API_KEY
        sync: false
